var quote_collection = { "Harry Potter": ["'Fear of a name only increases fear of the thing itself.' - Hermione Granger", "'It takes a great deal of bravery to stand up to our enemies, but just as much to stand up to our friends.' - Albus Dumbledore", "'But you know, happiness can be found even in the darkest of times, if one only remembers to turn on the light.' - Albus Dumbledore", "'There will be no foolish wand-waving or silly incantations in this class. As such, I don't expect many of you to appreciate the subtle science and exact art that is potion-making. However, for those select few who possess the predisposition, I can teach you how to bewitch the mind and ensnare the senses. I can tell you how to bottle fame, brew glory, and even put a stopper in death. Then again, maybe some of you have come to Hogwarts in possession of abilities so formidable that you feel confident enough to not pay attention!' - Professor Severus Snape", "'Just because you have the emotional range of a teaspoon doesn't mean we all have.' - Hermione Granger", "'It matters not what someone is born, but what they grow to be.' - Albus Dumbledore", "'Do not pity the dead, Harry. Pity the living, and, above all those who live without love.' - Albus Dumbledore", "'It is the unknown we fear when we look upon death and darkness, nothing more.' - Albus Dumbledore", "'You think the dead we loved ever truly leave us? You think that we don't recall them more clearly than ever in times of great trouble?' - Albus Dumbledore", "'It was, he thought, the difference between being dragged into the arena to face a battle to the death and walking into the arena with your head held high. Some people, perhaps, would say that there was little to choose between the two ways, but Dumbledore knew - and so do I, thought Harry, with a rush of fierce pride, and so did my parents - that there was all the difference in the world.' - Harry Potter", "'We've all got both light and dark inside us. What matters is the part we choose to act on. That's who we really are.' - Sirius Black", "'Things we lose have a way of coming back to us in the end, if not always in the way we expect.' - Luna Lovegood", "'I solemnly swear I am up to no good.' - Harry Potter", "'I am what I am, an' I'm not ashamed. 'Never be ashamed,' my ol' dad used ter say, 'there's some who'll hold it against you, but they're not worth botherin' with.'' - Rubeus Hagrid", "'Anything's possible if you've got enough nerve.' - Ginny Weasley", "'To the well-organized mind, death is but the next great adventure.' - Albus Dumbledore", "'I think we've outgrown full-time education ... Time to test our talents in the real world, d'you reckon?' - Fred Weasley", "'Every human life is worth the same, and worth saving.' - Kingsley Shacklebolt", "'For in dreams we enter a world that is entirely our own.' - Albus Dumbledore", "''He must have known I'd run out on you.' 'No,' Harry corrected him. 'He must've always known you'd always want to come back.'' - Ron Weasley", "'And now, Harry, let us step out into the night and pursue that flighty temptress, adventure.' - Albus Dumbledore", "'It is a curious thing, Harry, but perhaps those who are best suited to power are those who have never sought it. Those who, like you, have leadership thrust upon them, and take up the mantle because they must, and find to their own surprise that they wear it well.' - Albus Dumbledore", "'We're all going to keep fighting, Harry. You know that?' - Neville Longbottom", "'I am not worried, Harry...I am with you.' - Albus Dumbledore", "'Words are, in my not-so-humble opinion, our most inexhaustible source of magic. Capable of both inflicting injury, and remedying it.' - Albus Dumbledore", "'Time will not slow down when something unpleasant lies ahead.' - Harry Potter and the Goblet of Fire", "'Of course it is happening inside your head, Harry, but why on earth should that mean that it is not real?' - Albus Dumbledore", "'Celebrity is as celebrity does, remember that.' - Gilderoy Lockhart", "'Parents shouldn't leave their kids unless -unless they've got to.' - Harry Potter", "'Greatness inspires envy, envy engenders spite, spite spawns lies.' - Lord Voldemort", "'The happiest man on earth would be able to use the Mirror of Erised like a normal mirror, that is, he would look into it and see himself exactly as he is. Does that help.' - Albus Dumbledore", "'Hogwarts is threatened!' shouted Professor McGonagall.' Man the boundaries, protect us, do your duty to our school!' - Professor McGonagall", "'Killing is not so easy as the innocent believe.' - Harry Potter and the Half Blood Prince", "'That's what they should teach us here. How girls' brains work... It would be more useful than divination, anyway...' - Ron Weasley", "'What's comin' will come, and we'll meet it when it does.' - Rubeus Hagrid", "'Once again, you show all the sensitivity of a blunt axe.' - Nearly Headless Nick", "'From now on, I don't care if my tea leaves spell, 'Die, Ron, die,' I'm chucking them in the bin where they belong. - Ron Weasley", "'Have you any idea how much tyrants fear the people they oppress? All of them realize that, one day, amongst their many victims, there is sure to be one who rises against them and strikes back!' - Albus Dumbledore", "'Don't let the muggles get you down.' - Ron Weasley", "'There were near misses, many of them. We laughed about them afterwards. We were young, thoughtless - carried away with our own cleverness.' - Remus Lupin", "'We teachers are rather good at magic, you know.' - Minerva McGonagall", "'Differences of habit and language are nothing at all if our aims are identical and our hearts are open.' - Albus Dumbledore", "'You care so much you feel as though you will bleed to death with the pain of it.' - Harry Potter and the Order of the Phoenix", "'You will also find that help will always be given at Hogwarts to those who ask for it.' - Albus Dumbledore", "'But from that moment on, Hermione Granger became their friend. Because there are somethings you can't go through in life and become friends, and knocking out a twelve-foot mountain troll is one of them.' - Harry Potter and the Chamber of Secrets", "'Finally, the truth. Lying with his face pressed into the dusty carpet of the office where he had once thought he was learning the secrets of victory, Harry understood at last that he was not supposed to survive.' - Harry Potter and the Deathly Hallows", "'I was ripped from my body, I was less than spirit, less than the meanest ghost... But still, I was alive.' - Lord Voldemort", "'I mean, you could claim that anything's real if the only basis for believing in it is that nobody's proved it doesn't exist!' - Hermione Granger", "'How can I have hung round you for five years and not think girls are clever?' - Ron Weasley", "'The world isn't split into good people and Death Eaters.' - Sirius Black", "'No story lives unless someone wants to listen. The stories we love best do live in us forever. So whether you come back by page or by the big screen, Hogwarts will always be there to welcome you home.' - J.K. Rowling", "'I used to be self-conscious about my height, but then I thought, f-k that, I'm Harry Potter.' - Daniel Radcliffe", "'The line between Ron and me became thinner with each film and I think we became virtually the same person. There's a lot of me in Ron and moving on was a massive adjustment because it was such a constant part of my life.' - Rupert Grint ", "'When I see the images of the first Harry Potter, I immediately think of how ugly my hair was.' - Emma Watson", "'Harry Potter, to a point, will always define me, but I hope in the same way that Harrison Ford is defined by Star Wars.' - Daniel Radcliffe"], }

quote_collection["Benjamin Franklin"] = [
    "Fools multiply folly.",
    "The noblest question in the world is, What Good may I do in it?",
    "Early to bed, early to rise, makes a man healthy, wealthy and wise.",
    "Pay what you owe, and you'll know what's your own.",
    "An ounce of wit that is bought, is worth a pound that is taught.",
    "Hunger is the best pickle.",
    "Reading makes a full Man, Meditation a profound Man,|discourse a clear Man.",
    "Whate'er's begun in anger ends in shame.",
    "Fear to do ill, and you need fear naught else.",
    "A quarrelsome Man has no good Neighbors.",
    "If time be of all things the most precious, wasting time must be the greatest prodigality, since lost time is never found again; and what we call time enough always proves little enough. Let us then up and be doing, and doing to the purpose; so by diligence shall we do more with less perplexity.",
    "If you desire many things, many things will seem few.",
    "Well done is better than well said.",
    "He that sows thorns, should not go barefoot.",
    "Work as if you were to live 100 years, Pray as if you were to die To-morrow.",
    "Genius without education is like silver in the mine.",
    "Who is strong? He that can conquer his bad Habits.",
    "Don't go to the doctor with every distemper, nor to the lawyer with every quarrel, nor to the pot for every thirst.",
    "Distrust & caution are the parents of security.",
    "Avarice and Happiness never saw each other, how then shou'd they become acquainted.",
    "Wink at small faults; remember thou hast great ones.",
    "Proclaim not all thou knowest, all thou owest, all thou hast, nor all thou canst.",
    "Employ thy time well if thou meanest to gain leisure; and since thou art not sure of a minute, throw not away an hour. Leisure is time for doing something useful, and this leisure the diligent man will obtain, but the lazy man never, for a life of leisure and a life of laziness are two things.",
    "Reading makes a full man, meditation a profound man, discourse a clear man.",
    "Plough deep, while Sluggards sleep; And you shall have Corn, to sell and to keep.",
    "Better is a little with content than much with contention.",
    "Silence is not always a Sign of Wisdom, but Babbling is ever a Mark of Folly.",
    "You may give a Man an Office, but you cannot give him Discretion.",
    "Experience keeps a dear school; but fools will learn in no other, and scarce in that; for it is true, we may give advice, but we cannot give conduct.",
    "Dost thou love life? Then do not squander time, for that is the stuff life is made of.",
    "Search others for their virtues, thy self for thy vices.",
    "Sloth makes all things difficult, but industry, all things easy.—He that rises late must trot all day, and hall scarce overtake his business at night, while laziness travels so slowly that poverty soon overtakes him.",
    "Glass, China, and Reputation, are easily crack'd, and never well mended.",
    "Better slip with foot than tongue.",
    "If you'd know the Value of Money, go and borrow some.",
    "The Proud hate Pride—in others.",
    "God helps them that help themselves.",
    "Have you somewhat to do tomorrow; do it today.",
    "Wish not so much to live long as to live well.",
    "The worst wheel of the cart makes the most noise.",
    "Diligence overcomes Difficulties, Sloth makes them.",
    "Would you persuade, speak of Interest, not of Reason.",
    "An empty bag will not stand upright.",
    "He that can compose himself, is wiser than he that composes books.",
    "He's a Fool that cannot conceal his Wisdom.",
    "Having been poor is no shame, but being ashamed of it, is.",
    "If you desire many things, many things will seem but a few.",
    "Beware of him that is slow to anger: He is angry for some thing, and will not be pleased for nothing.",
    "Humility makes great men twice honourable.",
    "The Sting of a Reproach, is the Truth of it.",
    "How many observe Christ's Birth-day! How few, his Precepts! O! 'tis easier to keep Holidays than Commandments.",
    "Think of three Things, whence you came, where you are going, and to whom you must account.",
    "Virtue may not always make a Face handsome, but Vice will certainly make it ugly.",
    "To-morrow, every fault is to be amended; but that To-morrow never comes.",
    "The things which hurt, instruct.",
    "By diligence and patience, the mouse bit in two the cable.",
    "He that's content, hath enough; He that complains, has too much.",
    "If time be of all things most precious, wasting time must be the greatest prodigality, since lost time is never found again.",
    "Necessity never made a good bargain.",
    "A great Talker may be no Fool, but he is one that relies on him.",
    "Approve not of him who commends all you say.",
    "When the Well's dry, we know the Worth of Water.",
    "They that won't be counselled, can't be helped.",
    "Tell a miser he's rich, and a woman she's old, you'll get no money of one, nor kindness of t'other.",
    "Tell me my Faults, and mend your own. Men take more pains to mask than mend.",
    "The poor have little, beggars none, the rich too much, enough not one.",
    "Poverty wants some things, Luxury many things, Avarice all things.",
    "Wealth is not his that has it, but his that enjoys it.",
    "Anger is never without a Reason, but seldom with a good One.",
    "A Temper to bear much, will have much to bear.",
    "If Man could have Half his Wishes, he would double his Troubles.",
    "Lost time is never found again.",
    "Want of Care does us more Damage than Want of Knowledge.",
    "Hunger never saw bad bread.",
    "God helps them that help themselves.",
    "Speak little, do much.",
    "The Wolf sheds his Coat once a Year, his Disposition never.",
    "To err is human, to repent divine, to persist devilish.",
    "When you're good to others, you are best to yourself.",
    "He that waits upon fortune, is never sure of a dinner.",
    "Do not do what you would not have known.",
    "Haste makes waste.",
    "Beware of little expenses; a small leak will sink a great ship.",
    "He that is rich need not live sparingly, and he that can live sparingly need not be rich.",
    "Half the Truth is often a great Lie.",
    "Diligence is the mother of good luck.",
    "No gains without pains.",
    "There are lazy Minds as well as lazy Bodies.",
    "Be slow in chusing a Friend, slower in changing.",
    "He that lives upon Hope, dies fasting.",
    "The Sun never repents of the good he does, nor does he ever demand a recompence.",
    "Love, and be loved.",
    "What signifies your Patience, if you can't find it when you want it.",
    "Fish & visitors stink in 3 days.",
    "Sin is not harmful because it is forbidden, but it is forbidden because it is hurtful.",
    "Be neither silly, nor cunning, but wise.",
    "They who have nothing to be troubled at, will be troubled at nothing."
]